language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t leeondocks/docker-react -f ./client/Dockerfile.dev  ./client

script:
  - docker run -e CI=true leeondocks/docker-react npm run test

after_sucess:
  - docker build -t leeondocks96/multi-client ./client
  - docker build -t leeondocks96/multi-worker ./worker
  - docker build -t leeondocks96/multi-server ./server
  - docker build -t leeondocks96/multi-nginx  ./nginx
#Login to docker CLI
  - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
#Take built images and push to docker hub
  - docker push leeondocks96/multi-client
  - docker push leeondocks96/multi-worker
  - docker push leeondocks96/multi-server
  - docker push leeondocks96/multi-nginx

  